apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-tempapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-tempapp
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5 
  template:
    metadata:
      labels:
        app: web-tempapp
    spec:
      containers:
      - name: web-tempapp
        image: a2nacr.azurecr.io/vb/fahrenheitapp:88
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 300m
          limits:
            cpu: 500m
---
apiVersion: v1
kind: Service
metadata:
  name: web-tempapp
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: web-tempapp