apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
data:
  username: NTY3NmY5NmYtNmYxNi00ODdiLWE3NGYtNTA0ZjNlNGY2YWQ1
  password: dWo5OFF+M05jdjZ0dUo1M21CdU1ZeWRoUTE5MlhGSnI2RkhoU2EzYg==